# Generated by Django 5.2.4 on 2025-07-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood_diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('happy', 'Щасливий'), ('sad', 'Сумний'), ('angry', 'Злий'), ('neutral', 'Нейтральний'), ("I've had a fuck for everything", 'На все пофіг')], default='Undefined')),
                ('comment', models.TextField(max_length=200)),
            ],
        ),
    ]
